Create community health files.
FabricMC/.github pull request #1
Opened 2023-06-09 22:09 UTC by mineblock11

# `SUPPORT.md`

This will be linked under all issue and discussion sidebars in the "Support" link.

More information: 

https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/creating-a-default-community-health-file#supported-file-types

# Discussion Templates

2023-06-09 22:34 UTC, mineblock11 commented
Ready for review.

2023-06-10 16:04 UTC, modmuss50 requested changes

2023-06-10 16:04 UTC, modmuss50 commented on .github/DISCUSSION_TEMPLATE/mod-dev-support.yml
> +        - label: 'No'
Im not too sure how useful this is, most people will be using it, sometimes without knowing about it.

2023-06-10 16:04 UTC, modmuss50 commented on .github/DISCUSSION_TEMPLATE/player-support.yml
> +        client tokens or personal information exposed by your operating system.
I have never used this website thus dont really know how much I trust it. I dont think we should be guarenteing that it removes personal infomation.

The logs should never contain personal info, maybe other than your computer's username?

2023-06-10 16:04 UTC, modmuss50 commented on SUPPORT.md
> +- [Official Fabric Discord - `#player-support` and `#mod-dev` channels](https://discord.gg/v6v4pMv)
This whole section is a bit pointless atm, can add it back if/when these wiki pages are created.

2023-06-10 16:04 UTC, modmuss50 commented on SUPPORT.md
> +- [Fabric Loader](https://github.com/FabricMC/fabric-loader/issues)
Maybe add loom here as well 👍

2023-06-10 16:04 UTC, modmuss50 commented on SUPPORT.md
> +A full list of repositories in the Fabric toolchain [can be found here.](https://github.com/orgs/FabricMC/repositories)
Not too sure how useful this is tbh.

2023-06-10 16:04 UTC, modmuss50 commented on .github/DISCUSSION_TEMPLATE/player-support.yml
> +        Upload your logs **(if applicable)** to https://mclo.gs/ and paste the
Maybe dont specify a logs site here?

2023-06-10 16:04 UTC, modmuss50 commented on .github/DISCUSSION_TEMPLATE/player-support.yml
> +        client tokens or personal information exposed by your operating system.
Gist might be an alternative, they are already using github anyway.

2023-06-10 16:06 UTC, mineblock11 commented on .github/DISCUSSION_TEMPLATE/mod-dev-support.yml
> +        - label: 'No'
I was thinking the same, i'll probably just chuck it.

2023-06-10 16:13 UTC, mineblock11 commented
![image](https://github.com/FabricMC/.github/assets/93472213/987ca6b0-5bd7-48df-8e5e-9cdf7b7687c4)

2023-06-10 16:39 UTC, modmuss50 approved these changes
LGTM, this is something that we can easily change as we see how people use it 👍

2023-06-10 16:46 UTC, merged